### ISSUE TITLE
pre-channel FGSM

### ISSUE THREAD

**Issue by kwmcclintick** [brysef/rfml#2]
Hi Bryse,
I've added some for loops to your adversarial_evasion.py example to produce the plot below, and it seems like you're digitally inserting the FGSM attack directly into the data the eavesdropper receives, not adding it to your transmission pre-channel as in the paper this tutorial is associated with. Is there a simple way to do this with your API?
Best,
Kyle

![acc](https://user-images.githubusercontent.com/32203705/108926218-ef832800-760b-11eb-999f-a017c79c9345.png)

**Comment by brysef** [comment]
@kwmcclintick I'm a bit late, and I know you've already completed this project, but commenting here for others...

Yes, the eample script does indeed assume direct access to the eavesdropper -- this was studied in one of my papers where we showed that it works very well but argued that it's not realistic, for reasons you've mentioned. The example script was dumbed down to be as short as possible, the way the plots were generated for the publications involved custom generating the signals, applying FGSM, then applying the channel. This can all be done with the classes from within ptradio.
