### ISSUE TITLE
[Question] Any slides available?

### ISSUE THREAD

**Issue by austinmw** [brysef/rfml#3]
Hi, this seems like it was a great tutorial section. The notebooks are very helpful, but do you happen to have any slides that include the intro portion of the talk?

**Comment by brysef** [comment]
@austinmw Sorry I'm a bit late, but see attached if you're still interested.

[Flowers-Adversarial-RFML-with-PyTorch-Tut.pdf](https://github.com/user-attachments/files/17121388/Flowers-Adversarial-RFML-with-PyTorch-Tut.pdf)
