### ISSUE TITLE
[Question] ValueError: columns cannot be a set

### ISSUE THREAD

**Issue by zpsandzzc** [brysef/rfml#4]
I have downloaded the dataset, but encountered the following error when importing the dataset. How can I fix it?

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[22], line 1
----> 1 dataset = load_RML201610A_dataset(path=data_path)
      2 print(len(dataset))
      3 pprint(dataset.get_examples_per_class())

File G:\xxxcode\rfml-master\notebooks\..\rfml\data\converters\rml_2016.py:129, in load_RML201610A_dataset(path)
    121 UNPICKLED_PATH = "RML2016.10a_dict.pkl"
    123 loader = RML2016DataLoader(
    124     cache_path=CACHE_PATH,
    125     remote_url=REMOTE_URL,
    126     unpickled_path=UNPICKLED_PATH,
    127     warning_msg=WARNING_MSG,
    128 )
--> 129 return loader.load(path=path)

File G:\xxxcode\rfml-master\notebooks\..\rfml\data\converters\rml_2016.py:35, in RML2016DataLoader.load(self, path)
     30     if not os.path.exists(path):
     31         raise ValueError(
     32             "If path is provided, it must actually exist.  Provided path: "
     33             "{}".format(path)
     34         )
---> 35     return self._load_local(path=path)
     37 # If this function has previously been called before to fetch the dataset from the
     38 # remote, then it will have already been cached locally and unpickled.
     39 if os.path.exists(self.UNPICKLED_PATH):

File G:\xxxcode\rfml-master\notebooks\..\rfml\data\converters\rml_2016.py:53, in RML2016DataLoader._load_local(self, path)
     51         for iq in data[(mod, snr)]:
     52             builder.add(iq=iq, Modulation=mod, SNR=snr)
---> 53 return builder.build()

File G:\xxxcode\rfml-master\notebooks\..\rfml\data\dataset_builder.py:156, in DatasetBuilder.build(self)
    150 def build(self) -> Dataset:
    151     """Build the Dataset based on the examples that have been added.
    152 
    153     Returns:
    154         Dataset: A compiled dataset consisting of the added examples.
    155     """
--> 156     df = pd.DataFrame(self._rows, columns=self._keys)
    157     return Dataset(df)

File G:\Users\xxx\anaconda3\envs\LYY2\Lib\site-packages\pandas\core\frame.py:675, in DataFrame.__init__(self, data, index, columns, dtype, copy)
    673     raise ValueError("index cannot be a set")
    674 if columns is not None and isinstance(columns, set):
--> 675     raise ValueError("columns cannot be a set")
    677 if copy is None:
    678     if isinstance(data, dict):
    679         # retain pre-GH#38939 default behavior

**ValueError: columns cannot be a set**

**Comment by yoavay** [comment]
Same problem here...

**Comment by gawdygoda** [comment]
Try setting your pandas version to 1.4.4, the newer versions need some code fixes.
pip insatall pandas==1.4.4

Also, it looks like there is a PR to resolve this, I have not tried it yet however, you could also just clone that fork and work from there:

https://github.com/brysef/rfml/pull/5

**Comment by brysef** [comment]
Thanks @gawdygoda for alerting me to the activity here, #5 has been merged, hope it solves your issue! And thanks for @ArashSameni contribution.
